<?php
$title = 'Add New Album';
$this->headtitle($title);

?>

<h1> <?php echo $this->escapehtml($title)?> </h1>

<?php 
$form->setAttribute('action',$this->url('album',array('action'=>'add')));

$form->prepare();

echo $this->form()->openTag($form);
echo $this->formhidden($form->get('id'));
echo $this->formrow($form->get('title'));
echo $this->formrow($form->get('artist'));
echo $this->formsubmit($form->get('submit'));
echo $this->form()->closeTag();

?>